######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 31 03:53:55 2010
######################################################################

include("../tests.pri")

# Input
SOURCES += main.cpp
HEADERS += main.h
